# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2e18e9fe-ad72-4777-8cd6-ad27d6848403";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/863476eb-f012-4f3b-8ecf-1de2088e074d";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5cd87925-a753-47a6-a864-926383155f74";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/cf56dcab-ed5c-4c67-9f92-88b5473ecdca";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/55b725db-b8e9-43c2-94ab-bd1a37e9d73e"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
